### ISSUE TITLE
Session restoration chokes on crud objects during app server startup

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-server#100]
While starting up a servlet container after using the application, a number of exceptions are being logged to catalina.out. The problem is that these objects are being stored in user sessions and they aren't Serializable. there are multiple problems with this picture:
- These objects aren't safe for concurrent access, but will be used across multiple threads
- This design makes sessions heavy with what would mostly be stateless
- Session replication would choke on these as well, preventing usage of an application cluster

At the very least, session serialization should be restored, but this design should be reconsidered.

```
 java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.openhds.web.crud.impl.LocationHierarchyCrudImpl
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
...
Caused by: java.io.NotSerializableException: org.openhds.web.crud.impl.LocationHierarchyCrudImpl
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)

```

**Comment by batkinson** [comment]
This means the application won't work under normal usage as well. Servlet containers will move in-memory sessions to persistent storage after a period of inactivity or when the number of sessions grows past the point where they are using to much memory. When this happens, the crud objects will fail to persist (and hence won't be readable on when coming back into main memory) and will either:

  * lose the user's state if new objects are created to replace them
  * break the application for the user until their session is invalidated so it can be recreated

**Comment by batkinson** [comment]
With the removal of JSF (and in turn the session-scoped managed beans), this is no longer an issue.
