### ISSUE TITLE
Information lost for processing errors

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-server#190]
Affects the current production version, 4.5.

Jordan Smith reported that a number of forms failed to be processed successfully (they were marked with processed_ok as false in openhds.form_submission). After looking at this, the problem does *not* appear to be widespread. Out of 376,369 forms submitted, only 328 forms failed this way. That's approximately a 0.087% failure rate. While 100% would be nicer, I am not overly concerned with the overall impact this has if it is a defect. However, after looking closer I am not convinced this is a defect. However, I did find that diagnostic information may be getting lost.

In recent versions of the server software the error table was updated, along with accompanying code, to tie errors to the form submissions. Unfortunately, it is not offering much in the way of information. The log messages aren't giving enough information.

Here is an example: 

The stack trace only shows where the constraint violation was created from, not where it was thrown. Also, the 'null' message doesn't explain what the actual violation was. Combined with the fact that the error message collected in the table is just the exception class, it is difficult to piece together the constraints that are failing. However, it *is* clear that a constraint violation is the purpose for the processing failure.

```
2018-06-26 20:06:06.333  INFO 5 --- [taskScheduler-1] c.g.c.s.f.FormProcessor.formProcessor    : processing uuid:04825632-1c8d-4399-9387-fd36bb1821e9 (binding: individual)
2018-06-26 20:06:06.393 ERROR 5 --- [taskScheduler-1] c.g.c.s.f.FormProcessor.formProcessor    : failed to process submission

com.github.cimsbioko.server.exception.ConstraintViolations: null
        at com.github.cimsbioko.server.formproc.forms.IndividualFormProcessor.processForm(IndividualFormProcessor.java:55) ~[classes!/:4.5]
        at com.github.cimsbioko.server.formproc.forms.IndividualFormProcessor$$FastClassBySpringCGLIB$$f125a461.invoke(<generated>) ~[classes!/:4.5]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at com.github.cimsbioko.server.formproc.forms.IndividualFormProcessor$$EnhancerBySpringCGLIB$$c9b4b16c.processForm(<generated>) ~[classes!/:4.5]
        at jdk.nashorn.internal.scripts.Script$Recompilation$8$5690AA$\^eval\_.defaultProcess(<eval>:178) ~[na:na]
        at jdk.nashorn.internal.scripts.Script$Recompilation$5$4024A$\^eval\_.process(<eval>:136) ~[na:na]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1$2972$\^eval\_.processForms(<eval>:99) ~[na:na]
        at com.github.cimsbioko.server.formproc.FormProcessor$$NashornJavaAdapter.processForms(Unknown Source) [na:4.5]
        at com.github.cimsbioko.server.formproc.ScheduledProcessing.processForms(ScheduledProcessing.java:23) [classes!/:4.5]
        at com.github.cimsbioko.server.formproc.ScheduledProcessing$$FastClassBySpringCGLIB$$d7d1f06b.invoke(<generated>) [classes!/:4.5]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at com.github.cimsbioko.server.formproc.RunAsUserAspect.runAsUser(RunAsUserAspect.java:37) [classes!/:4.5]
        at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) [spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at com.github.cimsbioko.server.formproc.ScheduledProcessing$$EnhancerBySpringCGLIB$$b6450ddc.processForms(<generated>) [classes!/:4.5]
        at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

This should be improved to the point where we can easily comprehend the exact issue.

**Comment by batkinson** [comment]
It's worth noting that this particular form appears to have failed because the individual's extId conflicted with another existing individual. I did a lookup on the individual, and it's the same person at the same house, but a different individual uuid.

Here are the queries I used:
```sql
select * from openhds.form_submission f where instanceid = 'uuid:04825632-1c8d-4399-9387-fd36bb1821e9';
select * from openhds.error where submission = 'uuid:04825632-1c8d-4399-9387-fd36bb1821e9';
select * from openhds.fieldworker where uuid = '1ba9cf97e74942409750f31991866ae9';
select * from openhds.location where uuid = '7e3ef6c69cfd11e4a83b024ad57fbbd7';
select * from openhds.individual where uuid = '1043f9117ba04cbea765d97a35410357';
select * from openhds.individual where extId = 'M0336S020E004P01-001';
```
