### ISSUE TITLE
Hibernate 4 upgrade broke spring webflow pages

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-server#94]
Found as part of #92, it appears that we broke major portions of the user interface when we upgraded to Hibernate 4, but didn't detect it. Specifically, it appears that anything that was built on top of Spring webflow is failing due to incompatibilities caused by changes to the SessionFactory class as described by https://jira.spring.io/browse/SWF-1534.

You can see this by visiting URLs using webflow, such as:

  * /openhds/baseline.flow
  * /openhds/update.flow
  * /openhds/pregnancy-outcome.flow
  * /openhds/individualHistory.flow
  * /openhds/modifyHOH.flow
  * /openhds/deathForHOH.flow

Visiting them shows a stack trace that obscures the underlying problem, due to a defect in the openfaces ResourceFilter when attempting to unravel exception causes:

```
java.lang.ClassCastException: java.lang.NoSuchMethodError cannot be cast to java.lang.Exception
    org.openfaces.util.ResourceFilter.doFilter(ResourceFilter.java:105)
    org.openhds.web.util.OpenFacesResourceFilter.doFilter(OpenFacesResourceFilter.java:33)
```

By setting a breakpoint at ResourceFilter line 101, I was able to see the actual root cause:

```
Caused by: java.lang.NoSuchMethodError: org.hibernate.SessionFactory.openSession()Lorg/hibernate/classic/Session;
	at org.springframework.webflow.persistence.HibernateFlowExecutionListener.createSession(HibernateFlowExecutionListener.java:178)
	at org.springframework.webflow.persistence.HibernateFlowExecutionListener.sessionStarting(HibernateFlowExecutionListener.java:115)
	at org.springframework.webflow.engine.impl.FlowExecutionListeners.fireSessionStarting(FlowExecutionListeners.java:117)
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:363)
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:222)
	at org.springframework.webflow.executor.FlowExecutorImpl.launchExecution(FlowExecutorImpl.java:140)
	at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:193)
```

I was able to track this down to SWF-1534 from there.

**Comment by batkinson** [comment]
Upgrading to spring-webflow-2.4 or greater fixes the issue, but breaks other functionality due to other dependency incompatibilities.

**Comment by batkinson** [comment]
After downgrading, much of the behavior returned to the UI as expected, but I did notice a slight performance decrease for bulk operations such as xml cache file generation. We should be able to revisit Hibernate 4 if we can successfully upgrade to JSF 2 (currently the JSF config file says we are already using 2.0, but the libraries are not in agreement).
