### ISSUE TITLE
Attempting to delete an individual causes an AssertionFailure

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-server#97]
When attempting to delete an individual via the 'Individual' interface under the 'Amendments' menu, it yields the following:

````
Caused by: org.hibernate.AssertionFailure: collection [org.openhds.domain.model.Individual.allRelationships2] was not processed by flush()
	at org.hibernate.engine.CollectionEntry.postFlush(CollectionEntry.java:228)
	at org.hibernate.event.def.AbstractFlushingEventListener.postFlush(AbstractFlushingEventListener.java:356)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1206)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:375)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:657)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy518.delete(Unknown Source)
````

Searching through older issues, I found the same behavior reported in #41 and the upgrade to Hibernate 4 referenced in that issue "solved" the problem, but also broke all web flow pages as noted recently in #94. 

Ultimately, the real problem in #41 was not actually a defect in Hibernate. It was really our abuse of the Validator framework to do deep domain validations that cause uninitialized proxies to be loaded during a flush, which is intended to make the objects made dirty in the Session consistent with their database representations. Ultimately, additional objects should not be added to the Session once the flush operation starts, but Hibernate 4 was changed to allow it. This can create consistency problems especially when the loaded objects are modified.

There are multiple ways to address the problem:

  * Eagerly load all objects that have complex validations prior to operations that will cause a flush
  * Change complex validations to run on only on initialized objects, preventing lazy loading
  * Run validations prior to operations causing a flush, preventing lazy loads during flush
  * Migrate complex validation to a more appropriate place, not validation framework rules
  * Use a separate session within validation rule implementations requiring additional loads

There are likely more variations. In my opinion, the correct solution is to use validation as it was intended and move complex domain rules to domain-related code. Of the options above, it's the most consistent with the intended usage and it's the least likely to yield in unexpected consequences.

**Comment by batkinson** [comment]
After looking into this further it appears that we're actually performing the same validations twice. We manually use the validator framework where we create and edit data. However, the same rules run again when Hibernate flushes changes to the database, because putting hibernate-validator on the classpath automatically registers it to do so. It turns out that we would have had many more problems if this was not the case - by running validations prior to session flush, our complex validations, requiring lazy loading of uninitialized objects, already load the objects so validator won't load them during the flush phase. If it had, we would have seen more AssertionErrors " not processed by flush()". Simply disabling the automatic validation leaves us with just the validations that we coded. This includes all of the crud objects for the major entities in the system as well as the resource endpoints used to accept XML submissions from mirth.
